//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPdotNetMVCframework.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductTable
    {
        public int productId { get; set; }

        [Required(ErrorMessage = "product name required")]
        public string productName { get; set; }
        [Required(ErrorMessage = "product price required")]
        public Nullable<int> productPrice { get; set; }
    }
}
